### PR TITLE
Enable passing additional options to getWorkspaceProjects method.

### PR DESCRIPTION
**Pull request by livewyer**
Otherwise we're restricted to only retrieving active projects.  https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspaces.md

### CODE REVIEW

**Comment by livewyer** [comment]
Added equivalent change to TogglApi::getWorkspaceTasks() to accept options for filtering response.

**Comment by Rubatharisan** [comment]
I apologize @livewyer, I will look into this pull request now.

**Comment by livewyer** [comment]
Great, thanks! I might be able to stop using our fork now :)

On August 24, 2017 3:56:26 AM CDT, Rubatharisan Thirumathyam <notifications@github.com> wrote:
>Rubatharisan approved this pull request.
>
>Thank you @livewyer, it's added now :) 
>Have a great day,
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Morning-Train/toggl-api/pull/6#pullrequestreview-58315101

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Rubatharisan** [comment]
I am sorry for the delay, @livewyer :) 
Keep up the good work,

**Pull request merged**
