### PR TITLE
Fixed some little things

### PR DESCRIPTION
**Pull request by eyeonx**

### CODE REVIEW

**Comment by Rubatharisan** [comment]
Thank you for the changes eyeonx!

**Comment by eyeonx** [comment]
It's a pleasure :)

**Comment by MohamedBoualleg** [comment]
@Rubatharisan @eyeonx hey guys. Please be aware that the changes to the function name `getDashboardForWorkspace()` will break backward compatibility

**Comment by Rubatharisan** [comment]
Hey Mohamed, 
I agree - I have noted it under README - but is there anything different I can do to ensure backward compatibility?

Maybe: 
func.. getDashboadForWorkspace(*){
getDashboardForWorkspace(*)
}

Thank you Mohamed for your insight :)

**Comment by MohamedBoualleg** [comment]
@Rubatharisan what you proposed will solve the compatibility issue and it will be even better to mark the function a deprecated and then remove it in the next major release.

```
/**
 * @deprecated
 */
getDashboadForWorkspace(){
    getDashboardForWorkspace()
}
```
sorry for the late reply :)

**Pull request merged**
