### PR TITLE
Introduce coding standards (part2) 

### PR DESCRIPTION
**Pull request by derhasi**
As follow-up of #2 I also changed the rest of the coding style issues.

### CODE REVIEW

**Comment by Rubatharisan** [comment]
Hey @derhasi 
I added us to the Travis-CI.org, our page is https://travis-ci.org/Morning-Train/toggl-api
Can you let me know if I set it up correctly? 
Is there anything I need to change? 

Best regards,
Ruba

**Comment by derhasi** [comment]
@Rubatharisan, looks like PR-checks are working.

When you enable "Build pushes" in [settings](https://travis-ci.org/Morning-Train/toggl-api/settings) you should also have checks for the master branch. The master branch would fail before merging this PR. but try it out, so you can see the CI run fail for master. And after merging the build should pass, like this PR does.

**Comment by Rubatharisan** [comment]
@derhasi 
How can I enable the checks for master branch? 
I can't see any options saying "Build master branch" or anything alike? 
It seems like I only can build pull requests. 

image

Is this something I should enable in .travis.yml?

**Comment by derhasi** [comment]
@Rubatharisan it is the "Build pushes" option, so any push to any branch will be tested (unless only [specific branches are configured in the travis yml](https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches)).
But it will only take new pushes into account. So master will only build, when you push a new commit to master.

**Comment by Rubatharisan** [comment]
@derhasi ah okay that makes sense! 
I'll wait till a new commit will appear :) 

Thank you 👍

**Comment by Rubatharisan** [comment]
Have now reviewed the changes, will now merge this pull request,
Thank you @derhasi for the changes!

**Pull request merged**
